services:
  citizen_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args: &env
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        ALLOWED_HOSTS: ${ALLOWED_HOSTS:-0.0.0.0,localhost}
        IS_PRODUCTION: ${IS_PRODUCTION:-False}
        BASE_URL: ${BASE_URL}
    environment: *env
    ports:
      - ${CITIZEN_FRONTEND_PORT:-8000}:${CITIZEN_FRONTEND_PORT:-8000}
    develop:
      watch:
        - action: sync
          path: ./citizen_frontend
          target: app/citizen_frontend/
          ignore:
            - tests/
        - action: sync
          path: ./config
          target: app/config/
        - action: sync
          path: ./static
          target: app/static/
        - action: rebuild
          path: ./uv.lock
          target: app/uv.lock