import os

BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")
SERVICE_SLUG = "apply-for-a-licence"
TEMP_EVENT_SLUG = "temporary-event-notice"
FOOD_PREMISES_APPLICATION_SLUG = "food-premises-approval-6"
TEST_AUTH_SLUG = "winchester"
TEST_INTERACTION = "apply"
TEST_INTERATION_SUB_ID = "1"

TEST_TEMP_EVENT_APPLY_URL = (
    f"{BASE_URL}/{SERVICE_SLUG}/{TEMP_EVENT_SLUG}/{TEST_AUTH_SLUG}/{TEST_INTERACTION}-{TEST_INTERATION_SUB_ID}"
)

TEST_FOOD_PREMISES_APPLY_URL = (
    f"{BASE_URL}/{SERVICE_SLUG}/"
    f"{FOOD_PREMISES_APPLICATION_SLUG}/{TEST_AUTH_SLUG}/{TEST_INTERACTION}-{TEST_INTERATION_SUB_ID}"
)

TEST_TEMP_EVENT_APPLY_FORM_URL = (
    f"/{SERVICE_SLUG}/{TEMP_EVENT_SLUG}/{TEST_AUTH_SLUG}/{TEST_INTERACTION}-{TEST_INTERATION_SUB_ID}/form"
)

TEST_FOOD_PREMISES_APPLY_FORM_URL = (
    f"/{SERVICE_SLUG}/{FOOD_PREMISES_APPLICATION_SLUG}/"
    f"{TEST_AUTH_SLUG}/{TEST_INTERACTION}-{TEST_INTERATION_SUB_ID}/form"
)
