name: PR Checks
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff linting and format
    uses: ./.github/workflows/format.yaml
    with:
      build_branch: ${{ github.event.pull_request.head.ref }}


  test_ui:
    name: Playwright Tests
    uses: ./.github/workflows/playwright.yaml
    with:
      build_branch: ${{ github.event.pull_request.head.ref }}